# Generated by Django 4.1.4 on 2022-12-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_course_programme_student_section_question_plo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student", name="date_of_birth", field=models.DateField(),
        ),
    ]
